### Get channels
GET http://localhost:3000/channels/
Authorization: Bearer 0123456789

### Create channel

POST http://localhost:3000/channels/
Authorization: Bearer 0123456789
Content-Type: application/json

{
	"name": "TheBoys"
}

### Join Channel

POST http://localhost:3000/channels/ac5ab473-fd9b-41f6-a1b5-bb4ed6941410/join
Authorization: Bearer 123456789

### Leave Channel

DELETE http://localhost:3000/channels/1/join
Authorization: Bearer 123456789