### Get channels
GET http://localhost:3000/channels/

### Create channel

POST http://localhost:3000/channels/
Authorization: Bearer 1
Content-Type: application/json

{
	"name": "42"
}

### Join Channel

POST http://localhost:3000/channels/6f314b24-e2b3-49b4-b0c8-8a3de6263811/join
Authorization: Bearer 2

### Leave Channel -- not implemented

DELETE http://localhost:3000/channels/1/join
Authorization: Bearer 123456789
